### ISSUE TITLE
Running on results from doublet detecting softwares

### ISSUE THREAD

**Issue by drneavin** [13308204545/Chord#6]
Hello,

I am interested in trying chord on some datasets that I have where doublet detecting softwares have already been run. For example, I have a table that contains the results from scds, DoubletFinder, scDblFinder etc and I would like to apply chord to this table instead of creating a seurat object and rerunning each of these through chord. Could you confirm if this is possible or if you could help develop a function that could apply chord to this sort of table instead of an sce or seurat object?

Thanks for your help!

Best,
Drew

**Comment by 13308204545** [comment]
Hello Drew，
The operation of chord relies on generating simulated data sets and evaluating the accuracy of softwares in the simulated data sets. Therefore, it is not feasible to directly import existing computation a table.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "13308204545/Chord"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 中午1:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[13308204545/Chord] Running on results from doublet detecting softwares (Issue #6)





 
Hello,
 
I am interested in trying chord on some datasets that I have where doublet detecting softwares have already been run. For example, I have a table that contains the results from scds, DoubletFinder, scDblFinder etc and I would like to apply chord to this table instead of creating a seurat object and rerunning each of these through chord. Could you confirm if this is possible or if you could help develop a function that could apply chord to this sort of table instead of an sce or seurat object?
 
Thanks for your help!
 
Best,
 Drew

**Comment by drneavin** [comment]
Thanks @13308204545 , I had thought that might be the case but it's good to have it confirmed.
